spring:
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: http://localhost:5001/users
          predicates:
            - Path=/users/**
        - id: auth-route
          uri: http://localhost:5001/auth
          predicates:
            - Path=/auth/**